spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&options=-c%20TimeZone=Asia/Seoul
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  batch:
    jdbc:
      initialize-schema: always
    task:
      scheduling:
        cron:
          settlement: ${SETTLEMENT_CRON:-}

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}

settlement:
  async:
    enabled: ${SETTLEMENT_ASYNC:false}
    pool-size: ${SETTLEMENT_ASYNC_OLL_SIZE:5}
